name: cotfm
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.25.2
  - pytorch=2.2
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - torchaudio=2.2.2
  - torchvision=0.17.2
  - matplotlib
  - scipy
  - lightning
  - pysteps
  - pip
  - pip:
    - tqdm==4.64
    - torchcfm
    - torchdiffeq
    - jaxtyping
    - gpytorch
    - properscoring
    - wandb